// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"time"
)

type Client struct {
	ID         string    `json:"id"`
	FirstName  string    `json:"first_name"`
	MiddleName string    `json:"middle_name"`
	LastName   string    `json:"last_name"`
	FullName   string    `json:"full_name"`
	Email      string    `json:"email"`
	Message    string    `json:"message"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  string    `json:"updated_at"`
}

type Profile struct {
	ID            string    `json:"id"`
	UserID        string    `json:"user_id"`
	FirstName     string    `json:"first_name"`
	MiddleName    string    `json:"middle_name"`
	LastName      string    `json:"last_name"`
	FullName      string    `json:"full_name"`
	Email         string    `json:"email"`
	ContactNumber string    `json:"contact_number"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     string    `json:"updated_at"`
}

type User struct {
	ID                string    `json:"id"`
	Username          string    `json:"username"`
	Password          []byte    `json:"password"`
	PasswordUpdatedAt string    `json:"password_updated_at"`
	LastLogin         string    `json:"last_login"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
}
