// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func SideNav() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav id=\"side-nav\" class=\"h-20 bg-white flex flex-col py-4 px-4 items-center h-screen shadow-md fixed top-0 right-0\"><div hx-get=\"/close-nav\" hx-trigger=\"click\" hx-target=\"#side-nav\" hx-swap=\"outerHTML\" class=\"flex flex-row items-center justify-between\"><img src=\"/assets/xmark-solid.svg\" class=\"w-10 h-10 hover:scale-110 hover:rounded-md hover:border-2 hover:border-sky-100\" alt=\"company-logo\"><div class=\"w-52\"></div></div><div class=\"flex flex-col gap-10 items-center\"><ul class=\"flex flex-col justify-evenly gap-10 mt-4\"><li class=\"mx-5 cursor-pointer\"><a href=\"/\" class=\"text-sky-900 font-medium hover:border-b-2 hover:border-sky-900\">Home</a></li><li class=\"mx-5 cursor-pointer\"><a href=\"/projects\" class=\"text-sky-900 font-medium hover:border-b-2 hover:border-sky-900\">Projects</a></li><li class=\"mx-5 cursor-pointer\"><a href=\"/experience\" class=\"text-sky-900 font-medium hover:border-b-2 hover:border-sky-900\">Experience</a></li></ul><div class=\"mt-10\"><a href=\"/get-in-touch\" class=\"w-40 h-12 flex flex-row items-center justify-center transition ease-in-out delay-150 bg-sky-400 hover:scale-110 hover:bg-sky-600 duration-300 rounded-full text-white font-medium\">Get In Touch</a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
